# Generated by Django 5.0 on 2024-01-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Semister', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.semister')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staff.staff')),
            ],
        ),
    ]
