# Generated by Django 5.0 on 2023-12-21 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('father_name', models.CharField(max_length=35)),
                ('father_num', models.IntegerField()),
                ('mother_name', models.CharField(max_length=35)),
                ('Address', models.TextField(max_length=60)),
                ('Deparment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.deparment')),
                ('Semister', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.semister')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sess', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='account.sesson')),
            ],
        ),
    ]
