# Generated by Django 4.2.6 on 2023-12-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('roll', models.IntegerField()),
                ('father_name', models.CharField(max_length=35)),
                ('father_num', models.IntegerField()),
                ('mother_name', models.CharField(max_length=35)),
                ('Address', models.TextField(max_length=60)),
                ('Deparment', models.CharField(max_length=30)),
                ('sess', models.CharField(max_length=20)),
                ('Semister', models.CharField(max_length=20)),
            ],
        ),
    ]
